spring:
  application:
    name: deals-rest-api
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  liquibase:
    change-log: db/changelog/changelog-master.yaml
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            useProperties: false
            tablePrefix: QRTZ_
            clusterCheckinInterval: 5000
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadsInheritContextClassLoaderOfInitializingThread: true
    auto-startup: false
    overwrite-existing-jobs: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: none
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
    listener:
      simple:
        default-requeue-rejected: false

rabbitmq:
  contractor-queue: deals_contractor_queue
  dead-exchange: deals_dead_exchange
  dead-queue: deal_contractor_dead_queue
  dead-contractor-exchange: deal_contractor_dead_exchange

server:
  port: 8082

auditlib:
  log-level: INFO
  enable-file-logging: true

jwt:
  access:
    secret: