spring:
  application:
    name: deals-rest-api
  config:
    import: database.yml
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  liquibase:
    change-log: db/changelog/changelog-master.yaml
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            useProperties: false
            tablePrefix: QRTZ_
            clusterCheckinInterval: 5000
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadsInheritContextClassLoaderOfInitializingThread: true
    auto-startup: false

server:
  port: 8081