spring:
  application:
    name: deals-rest-api
  config:
    import: database.yml
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  liquibase:
    change-log: db/changelog/changelog-master.yaml